language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - aitorbernalfalcon95@gmail.com
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS bd;'
script:
- mvn clean -Denvironment.type=develop --settings settings.xml
- mvn test -Denvironment.type=develop --settings settings.xml
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify --settings settings.xml
- mvn sonar:sonar -Dsonar.organization=chinegua-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=66fdb89a18dc9f04451845f2271b4fe4eff0630e
